In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("italy-covid-daywise.csv")

In [3]:
df

           date  new_cases  new_deaths  new_tests
0    2019-12-31        0.0         0.0        NaN
1    2020-01-01        0.0         0.0        NaN
2    2020-01-02        0.0         0.0        NaN
3    2020-01-03        0.0         0.0        NaN
4    2020-01-04        0.0         0.0        NaN
..          ...        ...         ...        ...
243  2020-08-30     1444.0         1.0    53541.0
244  2020-08-31     1365.0         4.0    42583.0
245  2020-09-01      996.0         6.0    54395.0
246  2020-09-02      975.0         8.0        NaN
247  2020-09-03     1326.0         6.0        NaN

[248 rows x 4 columns]

In [10]:
data = {
    "name" : ['ram','shyam','vishal'],
    "Age" : [20,14,21],
    "city" : ['Pune','Nashik','chatrapati sambhajinagar']
}

df = pd.DataFrame(data)

df.to_csv("Student.csv",index=False)
df.to_excel("Student.xlsx",index=False)
df.to_json("Student.json",index=False)

In [6]:
df

     name  Age                      city
0     ram   20                      Pune
1   shyam   14                    Nashik
2  vishal   21  chatrapati sambhajinagar